---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      environment: "infrastructure"
      project: "kafka"
      version: "2.2.168"
    name: "kafka"
  spec:
    ports:
    - port: 9092
      protocol: "TCP"
      targetPort: 9092
    selector:
      environment: "infrastructure"
      project: "kafka"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      environment: "infrastructure"
      project: "mysql"
    name: "mysql"
  spec:
    ports:
    - port: 3306
      protocol: "TCP"
      targetPort: 3306
    selector:
      environment: "infrastructure"
      project: "mysql"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      environment: "infrastructure"
      project: "zookeeper"
    name: "zookeeper"
  spec:
    ports:
    - name: "client"
      port: 2181
      targetPort: 2181
    selector:
      project: "zookeeper"
      environment: "infrastructure"
- apiVersion: "v1"
  kind: "ConfigMap"
  metadata:
    labels:
      environment: "infrastructure"
      project: "zipkin-mysql"
      version: "0.1.5"
    name: "mysql-cnf"
  data:
    custom.cnf: "[mysqld]\nsql-mode=\"\"\n"
- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    labels:
      environment: "infrastructure"
      project: "kafka"
      version: "2.2.168"
    name: "kafka"
  spec:
    replicas: 1
    selector:
      environment: "infrastructure"
      project: "kafka"
      version: "2.2.168"
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: "Rolling"
    template:
      metadata:
        labels:
          environment: "infrastructure"
          project: "kafka"
          version: "2.2.168"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/kafka:2.2.168"
          imagePullPolicy: "IfNotPresent"
          name: "kafka"
          ports:
          - containerPort: 9092
            name: "kafka"
          - containerPort: 8778
            name: "jolokia"
          resources:
            limits:
              cpu: "0"
              memory: "0"
            requests:
              cpu: "0"
              memory: "0"
          securityContext:
            privileged: false
          volumeMounts:
          - mountPath: "/opt/kafka/logs"
            name: "logs"
            readOnly: false
        volumes:
        - emptyDir:
            medium: "Memory"
          name: "logs"
    triggers:
    - type: "ConfigChange"
- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    labels:
      environment: "infrastructure"
      project: "mysql"
      version: "0.1.5"
    name: "mysql"
  spec:
    replicas: 1
    selector:
      environment: "infrastructure"
      project: "mysql"
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: "Rolling"
    template:
      metadata:
        labels:
          environment: "infrastructure"
          project: "mysql"
          version: "0.1.5"
      spec:
        containers:
        - env:
          - name: "MYSQL_USER"
            value: "mysql"
          - name: "MYSQL_PASSWORD"
            value: "mysql"
          - name: "MYSQL_ROOT_PASSWORD"
            value: "mysql"
          - name: "MYSQL_DATABASE"
            value: "mysql"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "mysql:5.7"
          name: "mysql"
          readinessProbe:
            initialDelaySeconds: 5
            tcpSocket:
              port: 3306
          resources:
            limits:
              cpu: "0"
              memory: "0"
            requests:
              cpu: "0"
              memory: "0"
          volumeMounts:
          - mountPath: "/etc/mysql/conf.d/"
            name: "mysql-confd"
          - mountPath: "/var/lib/mysql/"
            name: "data"
        volumes:
        - configMap:
            name: "mysql-cnf"
          name: "mysql-confd"
        - emptyDir:
            medium: "Memory"
          name: "data"
    triggers:
    - type: "ConfigChange"
- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    labels:
      environment: "infrastructure"
      project: "zookeeper"
      version: "2.2.153"
      serverId: "1"
    name: "zookeeper"
  spec:
    replicas: 1
    selector:
      environment: "infrastructure"
      project: "zookeeper"
      version: "2.2.153"
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: "Rolling"
    template:
      metadata:
        labels:
          environment: "infrastructure"
          project: "zookeeper"
          version: "2.2.153"
      spec:
        containers:
        - env:
          - name: "ENSEMBLE_SIZE"
            value: "1"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/zookeeper:2.2.153"
          imagePullPolicy: "IfNotPresent"
          name: "zookeeper"
          ports:
          - containerPort: 2181
            name: "zkclient"
          - containerPort: 8778
            name: "jolokia"
          resources:
            limits:
              cpu: "0"
              memory: "0"
            requests:
              cpu: "0"
              memory: "0"
          securityContext:
            privileged: false
          volumeMounts:
          - mountPath: "/opt/zookeeper/data"
            name: "data"
            readOnly: false
          - mountPath: "/opt/zookeeper/log"
            name: "log"
            readOnly: false
        volumes:
        - emptyDir:
            medium: "Memory"
          name: "data"
        - emptyDir:
            medium: "Memory"
          name: "log"
    triggers:
    - type: "ConfigChange"